use algo_ops::{AlgoChainConfig, AlgoOps};

// Committed cross-impl parity vector (source of truth:
// bingle_notify/test/fixtures/verify-vector.json, regenerated by scripts/gen-verify-vector.mjs).
// Ed25519 is deterministic, so a correct signer reproduces these signatures byte-for-byte, which
// is exactly what the gateway's algosdk.verifyBytes accepts.
const TEST_MNEMONIC: &str = "square flat curtain negative three april hobby culture unit fit drip bronze cactus stage vault pluck captain nation pond pizza grief domain coin abstract path";
const TEST_ADDRESS: &str = "JH2CPATVR25EJ4B2CQD7P5436MHXJOU2MZGIWPFPAB3JBNVX3CGQDLDENU";
const TEST_NONCE: &str = "BBBBBBBBBBBBBBBBBBBBBB";
const TEST_EXP: i64 = 1893456000;

fn default_cfg() -> AlgoChainConfig {
    // No network calls are made in these tests, but AlgoOps requires a config.
    AlgoChainConfig::default()
}

fn test_ops() -> AlgoOps {
    let ops = AlgoOps::new(Some(TEST_MNEMONIC.to_string()), None, Some(default_cfg()));
    assert_eq!(
        ops.address.as_deref(),
        Some(TEST_ADDRESS),
        "test vector mnemonic must derive the expected address"
    );
    ops
}

#[test]
#[cfg(not(target_os = "ios"))]
pub fn signs_register_envelope_matching_the_committed_vector() {
    // register case: iss="alice", audience="", token="device-token-abc", env="sandbox".
    let sig = test_ops()
        .sign_notify_envelope(
            "register",
            "alice",
            "",
            "device-token-abc",
            "sandbox",
            TEST_NONCE,
            TEST_EXP,
        )
        .expect("register envelope should sign");
    assert_eq!(
        sig,
        "x/Xuu41OFj2kEqfos74PuFcrXrjfWW14ys8lYxyX+e9F7D8Q0iUwE+82ayIRPXFN4IfzwNDK+flzHRvkwxfwBA=="
    );
}

#[test]
#[cfg(not(target_os = "ios"))]
pub fn register_signature_is_deterministic() {
    let ops = test_ops();
    let a = ops
        .sign_notify_envelope(
            "register",
            "alice",
            "",
            "device-token-abc",
            "sandbox",
            TEST_NONCE,
            TEST_EXP,
        )
        .expect("should sign");
    let b = ops
        .sign_notify_envelope(
            "register",
            "alice",
            "",
            "device-token-abc",
            "sandbox",
            TEST_NONCE,
            TEST_EXP,
        )
        .expect("should sign");
    assert_eq!(a, b, "Ed25519 signing must be deterministic");
}

#[test]
#[cfg(not(target_os = "ios"))]
pub fn rejects_unknown_route() {
    let result =
        test_ops().sign_notify_envelope("bogus", "alice", "", "", "", TEST_NONCE, TEST_EXP);
    assert!(result.is_err(), "an unknown route must not sign");
}

#[test]
#[cfg(not(target_os = "ios"))]
pub fn signing_requires_account_access() {
    // No passphrase → no key → cannot sign.
    let ops = AlgoOps::new_indexer(Some(default_cfg()));
    let result = ops.sign_notify_envelope("alert", "alice", "bob", "", "", TEST_NONCE, TEST_EXP);
    assert!(
        result.is_err(),
        "signing without account access must fail rather than produce a bogus signature"
    );
}
